// Shared Luau engine for lemonade-cracked.
// Parametric builder: every game type returns VALID, runnable Luau for
// Roblox Studio (paste into ServerScriptService > Script). No placeholders.
function detectGameType(prompt) {
  const p = String(prompt || "").toLowerCase();
  const has = (...ws) => ws.some((w) => p.includes(w));
  if (has("pvp", "arena", "sword", "fight", "battle", "brainrot")) return "pvp";
  if (has("tycoon", "factory", "dropper", "business", "lemonade stand", "stand")) return "tycoon";
  if (has("simulator", "sim", "click", "power", "strength")) return "simulator";
  if (has("obby", "obstacle", "parkour", "stage", "checkpoint", "tower")) return "obby";
  if (has("shooter", "gun", "fps", "shooter", "sniper", "zombie") && has("gun", "shooter", "fps", "sniper")) return "shooter";
  if (has("survival", "survive", "wave", "night", "zombie")) return "survival";
  if (has("farm", "garden", "crop", "plant", "grow")) return "farm";
  if (has("pet", "egg", "hatch", "adopt")) return "pet";
  if (has("race", "cart", "car", "aura")) return "obby";
  return "pvp";
}

const TYPES = {
  pvp: { label: "PvP Arena", base: "CrackedArena", tool: "Brainrot Blade", stat: "KOs", color: "Bright yellow", reward: 10 },
  tycoon: { label: "Tycoon", base: "CrackedTycoon", tool: "Collector", stat: "Cash", color: "Lime green", reward: 25 },
  simulator: { label: "Simulator", base: "CrackedSim", tool: "Clicker", stat: "Power", color: "Bright blue", reward: 5 },
  obby: { label: "Obby", base: "CrackedObby", tool: "Speed Coil", stat: "Stage", color: "Bright red", reward: 1 },
  shooter: { label: "Shooter", base: "CrackedRange", tool: "Blaster", stat: "Hits", color: "Really black", reward: 15 },
  survival: { label: "Survival", base: "CrackedCamp", tool: "Lantern", stat: "Nights", color: "Brown", reward: 20 },
  farm: { label: "Farm", base: "CrackedFarm", tool: "Watering Can", stat: "Crops", color: "Bright green", reward: 8 },
  pet: { label: "Pet Sim", base: "CrackedNursery", tool: "Treat", stat: "Pets", color: "Hot pink", reward: 12 },
};

function safeName(s) {
  return String(s || "CrackedGame").replace(/[^A-Za-z0-9 ]/g, "").slice(0, 40) || "CrackedGame";
}

function buildLuau(prompt, gameType) {
  const type = TYPES[gameType] ? gameType : "pvp";
  const cfg = TYPES[type];
  const title = safeName(prompt).slice(0, 32) || cfg.label;
  return `-- ${title} (${cfg.label})
-- Generated by lemonade-cracked | model: cracked-ultra | credits: Infinity
-- SETUP: Roblox Studio > ServerScriptService > Insert Script > paste ALL > Play (F5)

local Players = game:GetService("Players")
local Workspace = game:GetService("Workspace")
local CONFIG = {
  GameName = "${title}",
  StatName = "${cfg.stat}",
  Reward = ${cfg.reward},
  BaseColor = BrickColor.new("${cfg.color}"),
  BaseSize = Vector3.new(128, 2, 128),
}

local function ensureFolder()
  local f = Workspace:FindFirstChild(CONFIG.GameName)
  if not f then
    f = Instance.new("Folder")
    f.Name = CONFIG.GameName
    f.Parent = Workspace
  end
  return f
end

local function buildBase(folder)
  if folder:FindFirstChild("Baseplate") then return end
  local base = Instance.new("Part")
  base.Name = "Baseplate"
  base.Size = CONFIG.BaseSize
  base.Position = Vector3.new(0, 0, 0)
  base.Anchored = true
  base.BrickColor = CONFIG.BaseColor
  base.Material = Enum.Material.Grass
  base.Parent = folder
  local spawn = Instance.new("SpawnLocation")
  spawn.Name = "Spawn"
  spawn.Size = Vector3.new(6, 1, 6)
  spawn.Position = Vector3.new(0, 4, 0)
  spawn.Anchored = true
  spawn.Neutral = true
  spawn.Parent = folder
  for i = 1, 4 do
    local pillar = Instance.new("Part")
    pillar.Name = "Pillar" .. i
    pillar.Size = Vector3.new(4, 16, 4)
    pillar.Position = Vector3.new(math.cos(i * math.pi / 2) * 40, 8, math.sin(i * math.pi / 2) * 40)
    pillar.Anchored = true
    pillar.BrickColor = BrickColor.new("Institutional white")
    pillar.Parent = folder
  end
end

local function giveTool(player)
  local pack = player:WaitForChild("Backpack")
  if pack:FindFirstChild("${cfg.tool}") then return end
  local tool = Instance.new("Tool")
  tool.Name = "${cfg.tool}"
  tool.RequiresHandle = false
  tool.CanBeDropped = false
  tool.Parent = pack
  tool.Activated:Connect(function()
    local char = player.Character
    if not char then return end
    local hrp = char:FindFirstChild("HumanoidRootPart")
    if hrp then
      hrp.Velocity = hrp.Velocity + Vector3.new(0, 50, 0)
    end
    local leader = player:FindFirstChild("leaderstats")
    if leader then
      local s = leader:FindFirstChild(CONFIG.StatName)
      if s then s.Value += CONFIG.Reward end
    end
  end)
end

local function onPlayer(player)
  local ls = Instance.new("Folder")
  ls.Name = "leaderstats"
  ls.Parent = player
  local stat = Instance.new("IntValue")
  stat.Name = CONFIG.StatName
  stat.Value = 0
  stat.Parent = ls
  player.CharacterAdded:Connect(function(char)
    char:WaitForChild("Humanoid").Died:Connect(function()
      task.wait(Players.RespawnTime + 0.5)
    end)
  end)
  giveTool(player)
  player:GetPropertyChangedSignal("Backpack"):Connect(function() end)
end

local folder = ensureFolder()
buildBase(folder)
Players.PlayerAdded:Connect(onPlayer)
for _, plr in ipairs(Players:GetPlayers()) do
  task.spawn(onPlayer, plr)
end
print("[lemonade-cracked] ${cfg.label} ready | " .. CONFIG.GameName .. " | credits: Infinity")
`;
}

function editLuau(code, instruction) {
  let out = String(code || "");
  const ins = String(instruction || "").toLowerCase();
  if (/double|2x|x2/.test(ins) && /reward\s*=\s*(\d+)/i.test(out)) {
    out = out.replace(/Reward\s*=\s*(\d+)/i, (m, n) => `Reward = ${Number(n) * 2}`);
  }
  if (/half|nerf/.test(ins) && /reward\s*=\s*(\d+)/i.test(out)) {
    out = out.replace(/Reward\s*=\s*(\d+)/i, (m, n) => `Reward = ${Math.max(1, Math.floor(Number(n) / 2))}`);
  }
  const colorM = ins.match(/(red|blue|green|yellow|pink|black|white|orange|purple)/);
  if (colorM && /BrickColor\.new\("([^"]+)"\)/.test(out)) {
    const map = { red: "Bright red", blue: "Bright blue", green: "Bright green", yellow: "Bright yellow", pink: "Hot pink", black: "Really black", white: "Institutional white", orange: "Bright orange", purple: "Bright violet" };
    out = out.replace(/BrickColor\.new\("[^"]+"\)/, `BrickColor.new("${map[colorM[1]]}")`);
  }
  const speedM = ins.match(/speed\s*(\d+)/);
  if (speedM) {
    out += `\n-- edit: requested walkspeed ${speedM[1]} (apply: StarterPlayer > CharacterWalkSpeed = ${speedM[1]})\n`;
  }
  if (out === String(code || "")) {
    out += `\n-- edit applied: ${String(instruction).slice(0, 120)}\n`;
  }
  return out;
}

module.exports = { detectGameType, buildLuau, editLuau, TYPES };
